### ISSUE TITLE
Azure/go-amqp is breaking import compatibility rule, introduced in Go 1.11

### ISSUE THREAD

**Issue by filip-dahlberg** [Azure/go-amqp#172]
It seems like Azure/go-amqp is breaking the [import compatibility rule](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). I have two packages that that imports Azure/go-amqp. Since the definition of amqp.Message is not backwards compatible from Azure/go-amqp@0.17 to Azure/go-amqp@0.13, go vet ./... yields following error:

```sh
go vet ./...
# github.com/
message.Accept undefined (type *amqp.Message has no field or method Accept)
message.Reject undefined (type *amqp.Message has no field or method Reject)
message.Modify undefined (type *amqp.Message has no field or method Modify)
cannot use p.topic (variable of type string) as type *string in struct literal
```

**Comment by jhendrixMSFT** [comment]
We're in the process of stabilizing the API which is why the major version remains at `v0`.  Our POR is for a final round of API clean-up, then freeze the public surface area in a push for a `v1.0.0` release.

Sorry for the hassle this has caused.  In hindsight, we should have pushed for all the API clean-up first in one batch.
